### ISSUE TITLE
Problem with device connection.

### ISSUE THREAD

**Issue by antonkazakov** [bridgefy/bridgefy-android-samples#3]
When trying to connect device (Meizu M3 Note) to Nexus 5 there is no deviceConnected callback.

```
E/ChunkUtils: stitchChunksToEntity: UNDEFINE 221
E/ChunkUtils: stitchChunksToEntity: 
              java.util.zip.ZipException: Corrupt GZIP trailer
                  at java.util.zip.GZIPInputStream.readTrailer(GZIPInputStream.java:226)
                  at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:120)
                  at java.io.FilterInputStream.read(FilterInputStream.java:107)
                  at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
                  at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
                  at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
                  at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:462)
                  at com.bridgefy.sdk.framework.controller.ChunkUtils.decompress(SourceFile:494)
                  at com.bridgefy.sdk.framework.controller.ChunkUtils.a(SourceFile:325)
                  at com.bridgefy.sdk.framework.controller.p.onCharacteristicWriteRequest(SourceFile:267)
                  at android.bluetooth.BluetoothGattServer$1.onCharacteristicWriteRequest(BluetoothGattServer.java:206)
                  at android.bluetooth.IBluetoothGattServerCallback$Stub.onTransact(IBluetoothGattServerCallback.java:139)
                  at android.os.Binder.execTransact(Binder.java:697)
```

this is exception in logs.
But when i disable bluetooth on this device i receive deviceLost callback. How can I fix it?

**Comment by dustedrob** [comment]
Thank you for reporting this issue. Can you provide a more detailed log? (Preferably from the time that a connection is established to the point where this error happens) This will help us understand this scenario more clearly.
