### ISSUE TITLE
Runtime exception when switching on bluetooth and starting Bridgefy

### ISSUE THREAD

**Issue by androidlab** [bridgefy/bridgefy-android-samples#5]
Device: Moto G5 Plus

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xx.xxxxxx, PID: 28211
    java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.adapter.action.STATE_CHANGED flg=0x14000010 (has extras) } in com.bridgefy.sdk.framework.controller.a@ae993cd
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.bridgefy.sdk.client.BFEnergyProfile com.bridgefy.sdk.client.Config.getEnergyProfile()' on a null object reference
        at com.bridgefy.sdk.framework.controller.m.a(SourceFile:94)
        at com.bridgefy.sdk.framework.controller.h.a(SourceFile:166)
        at com.bridgefy.sdk.framework.controller.h.h(SourceFile:389)
        at com.bridgefy.sdk.framework.controller.h.d(SourceFile:350)
        at com.bridgefy.sdk.framework.controller.h.b(SourceFile:222)
        at com.bridgefy.sdk.framework.controller.h.a(SourceFile:456)
        at com.bridgefy.sdk.framework.controller.a.b(SourceFile:247)
        at com.bridgefy.sdk.framework.controller.a.a(SourceFile:104)
        at com.bridgefy.sdk.framework.controller.a.onReceive(SourceFile:54)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by dekaru** [comment]
Hi @androidlab, thank you for your report. Were you running one of the github samples or did this happen in your own implementation? Could you share with us the way you're building and setting the custom Config object, if you're setting it at all? Thanks.

**Comment by androidlab** [comment]
Hi @dekaru, this is happening in my own implementation. But I am not setting any Config object.

**Comment by dustedrob** [comment]
Hi @androidlab Can you provide the specific steps to reproduce this crash? If you can provide the code for your implementation (starting and stopping Bridgefy) that would be very helpful as well.
Thank you.

**Comment by androidlab** [comment]
Hi @dustedrob, 

I am using a receiver to start/stop Bridegfy.

        ```
if(BluetoothAdapter.ACTION_STATE_CHANGED.equals(action)){
            if (intent.getIntExtra(BluetoothAdapter.EXTRA_STATE, -1) == BluetoothAdapter.STATE_OFF) {
                // Bluetooth is disconnected, do handling here
                if(LocationHandler.isLocationEnabled(context)){
                    Intent i = new Intent(context, BridgefyService.class);
                    context.stopService(i);
                }
            }else{
                Intent i = new Intent(context, BridgefyService.class);
                context.startService(i);
            }

        }
```

In onStartCommand of BridgefyService

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {

        Bridgefy.initialize(context, "-----API---KEY--------",
                new RegistrationListener() {
                    @Override
                    public void onRegistrationSuccessful(BridgefyClient bridgefyClient) {
                        // Bridgefy is ready to start
                        Bridgefy.start(messageListener, stateListener);
                    }

                    @Override
                    public void onRegistrationFailed(int errorCode, String message) {
                        // Something went wrong: handle error code, maybe print the message
                        Log.d(TAG, message);
                    }
                });
}

**Comment by dustedrob** [comment]
@androidlab This is probably not the best implementation for a service running Bridgefy. I have a few observations:

- You should run initialize() outside the service, since it's only really necessary to run this method once
- It's not really necessary for you to manually check the Bluetooth states since Bridgefy already does this. You should ideally start the service regardless of whether Bluetooth is active, use Bridgefy.start() when the service is started and Bridgefy.stop() when the service is stopped.

**Comment by kekoyde** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/bridgefy/bridgefy-android-samples#bridgefy-android-sdk-v-1124).

Thank you!
