### ISSUE TITLE
Error registering Bridgefy

### ISSUE THREAD

**Issue by PiwanSama** [bridgefy/bridgefy-android-samples#7]
Hello. I recently when I started getting an error that won't allow me to register my android application with Bridgefy. This is the error message in the logcat:

`E/Bridgefy: Registration (Token Request) failed with http code: 500, body: 
    <html><head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <title>500 Server Error</title>
    </head>
    <body text=#000000 bgcolor=#ffffff>
    <h1>Error: Server Error</h1>
    <h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>
    <h2></h2>
    </body></html>
W/System.err: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at com.bridgefy.sdk.client.Bridgefy$1.run(SourceFile:240)
    Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
    	... 5 more`

Could this be an error in my code or a backend problem?

**Comment by kekoyde** [comment]
Sorry for the inconvenience, we improved our versions, this issue was fixed.
#9
